<?php
// 項目名日本語化用配列リスト
$Reg_Att_name = Array(
	'semi_id'=>'ＩＤ',
	'last_date'=>'最終更新日',
	'kaisu'=>'回',
	'gakkai'=>'学会名',
	'seminar'=>'セミナー名',//5
	'kaityo'=>'会長',
	'yaku'=>'役職',
	'ryoiki'=>'領域',
	'kaisaibi'=>'セミナー開催日',
	'kaisaiji'=>'開催時間', //10
	'nendo'=>'年度',
	'kaiki'=>'会期',
	'place'=>'会場',
	'syukan'=>'共催',
	'sekinin'=>'責任者', //15
	'thema'=>'テーマ',
	'chair1'=>'座長1',
	'chair2'=>'座長2',
	'cyaku1'=>'座長1役職',
	'cyaku2'=>'座長2役職', //20
	'enshaname1'=>'演者1',
	'enshaname2'=>'演者2',
	'enshaname3'=>'演者3',
	'enshaname4'=>'演者4',
	'enshayaku1'=>'演者1役職', //25
	'enshayaku2'=>'演者2役職',
	'enshayaku3'=>'演者3役職',
	'enshayaku4'=>'演者4役職',
	'endai1'=>'演題1',
	'endai2'=>'演題2', //30
	'endai3'=>'演題3',
	'endai4'=>'演題4',
	'hotel'=>'宿泊（ホテル）',
	'hinmoku'=>'品目',
	'cltantou'=>'ＣＬ窓口', //35
	'amail'=>'案内メール',        // T 36
	'annai1'=>'案内状作成',
	'annai2'=>'案内状送付',
	'yoko'=>'要綱入手',
	'iraijo'=>'依頼書・招聘状',   // T 40
	'oudaku'=>'応諾書',           // T 41
	'tirasi1'=>'チラシ作成依頼',  // T 42
	'tirasi2'=>'チラシ経過・完成',// T 43
	'tirasi3'=>'チラシ納品日',    // T 44
	'mousi_add'=>'追加申込',
	'mousi_c'=>'申込締切',
	'mousi_k'=>'申込内容確認',
	'syoroku'=>'抄録締切',        // T 48
	'kaijo_k'=>'会場確認',
	'hikae_k'=>'控室確認',
	'hikae_a'=>'控室名',  //       T 51
	'syuku_k'=>'宿泊確認',  //       T 52
	'tojitu'=>'当日配布物手配',  //  T 53
	'cv'=>'CV入手',  //              T 54
	'sharei'=>'謝金支払確認',  //    T 55
	'shaman1'=>'謝金氏名1',
	'shahi1'=>'謝金支払1',
	'shaman2'=>'謝金氏名2',
	'shahi2'=>'謝金支払2',
	'shaman3'=>'謝金氏名3',  // 60
	'shahi3'=>'謝金支払3',
	'shaman4'=>'謝金氏名4',
	'shahi4'=>'謝金支払4',
	'yakubun1'=>'分担表Ver1送付',
	'yakubun2'=>'分担表送付',  //    T 65
	'last_m'=>'最終Ｍ',
	'report'=>'事後報告書',  //      T 67
	'zaseki'=>'座席数',
	'bento'=>'弁当数',
	'nyujosha'=>'入場者数',         // 70
	'an_kaisyu'=>'アンケート回収者数',
	'status'=>'進行状況',
	'yobi1'=>'予備1',
	'yobi2'=>'予備2',
	'yobi3'=>'予備3',   // 75
	'yobi4'=>'予備4',
	'cl1'=>'CL予備1',
	'cl2'=>'CL予備2',
	'cl3'=>'CL予備3',
	'sys_stat'=>'sys_stat', // 80
	'narabi'=>'表示順'
	);
?>
